/**
 * ccnpQuestions.js
 *
 * An ORIGINAL CCNP-level question bank (Enterprise: ENCOR 350-401 + ENARSI
 * 300-410 topic outline). Written from scratch against the public blueprint —
 * nothing copied from Cisco courseware or any third-party question dump.
 *
 * Every question carries `track: 'CCNP'` so the Trainer can present CCNA and
 * CCNP as separate study sections over the same engine. Same shape as the CCNA
 * bank: { id, track, domain, difficulty, prompt, choices, correct, multi,
 * explanation, reference }.
 *
 * DOM-free data module.
 */

/** CCNP blueprint domains used for filtering in the Trainer. */
export const CCNP_DOMAINS = Object.freeze({
  ROUTING: 'Advanced Routing',
  SWITCHING: 'Enterprise Switching',
  REDUNDANCY: 'FHRP & High Availability',
  SERVICES: 'Network Services & QoS',
  OVERLAY: 'Overlay & Virtualization',
  SECURITY: 'Infrastructure Security',
  AUTOMATION: 'Automation & Programmability',
});

const D = CCNP_DOMAINS;

/**
 * @param {object} q
 * @returns {object} the question tagged as CCNP with sensible defaults.
 */
function q(item) {
  return {
    track: 'CCNP',
    multi: false,
    difficulty: 'Intermediate',
    reference: 'CCNP Enterprise',
    ...item,
  };
}

export const CCNP_QUESTIONS = Object.freeze([
  // --- Advanced Routing ------------------------------------------------
  q({
    id: 'np-ebgp-ad',
    domain: D.ROUTING,
    prompt: 'What is the default administrative distance of an external BGP (eBGP) route?',
    choices: [
      { id: 'a', text: '20' },
      { id: 'b', text: '110' },
      { id: 'c', text: '200' },
      { id: 'd', text: '90' },
    ],
    correct: ['a'],
    explanation:
      'eBGP routes have an AD of 20 (preferred over IGPs), while iBGP routes have an AD of 200 (less preferred than most IGPs).',
    reference: '350-401 ENCOR — BGP path attributes',
  }),
  q({
    id: 'np-bgp-first-attr',
    domain: D.ROUTING,
    difficulty: 'Advanced',
    prompt:
      'In the BGP best-path selection process, which attribute is evaluated FIRST (and prefers the highest value)?',
    choices: [
      { id: 'a', text: 'Weight (Cisco-proprietary, local to the router)' },
      { id: 'b', text: 'Local Preference' },
      { id: 'c', text: 'AS-Path length' },
      { id: 'd', text: 'MED' },
    ],
    correct: ['a'],
    explanation:
      'Cisco evaluates Weight first (highest wins); it is local to the router and not advertised. Local Preference comes next and IS shared within the AS.',
    reference: '350-401 ENCOR — BGP best path',
  }),
  q({
    id: 'np-eigrp-ad-internal',
    domain: D.ROUTING,
    prompt:
      'A prefix is learned via both OSPF and internal EIGRP. Which route is installed, and why?',
    choices: [
      { id: 'a', text: 'EIGRP, because its AD (90) is lower than OSPF (110)' },
      { id: 'b', text: 'OSPF, because it uses a link-state algorithm' },
      { id: 'c', text: 'EIGRP, because it always has a lower metric' },
      { id: 'd', text: 'Both are installed for load balancing' },
    ],
    correct: ['a'],
    explanation:
      'Administrative distance breaks ties between routing sources. Internal EIGRP (90) beats OSPF (110). External EIGRP, by contrast, is 170.',
    reference: '350-401 ENCOR — administrative distance',
  }),
  q({
    id: 'np-ospf-lsa5',
    domain: D.ROUTING,
    difficulty: 'Advanced',
    prompt: 'Which OSPF LSA type describes routes redistributed into OSPF from another protocol?',
    choices: [
      { id: 'a', text: 'Type 5 (External LSA)' },
      { id: 'b', text: 'Type 1 (Router LSA)' },
      { id: 'c', text: 'Type 3 (Summary LSA)' },
      { id: 'd', text: 'Type 2 (Network LSA)' },
    ],
    correct: ['a'],
    explanation:
      'Type 5 External LSAs are generated by an ASBR for redistributed routes and flooded through the domain (except into stub/NSSA areas).',
    reference: '300-410 ENARSI — OSPF LSA types',
  }),
  q({
    id: 'np-ospf-stub',
    domain: D.ROUTING,
    difficulty: 'Advanced',
    prompt:
      'Which OSPF area type blocks Type 5 (external) LSAs but still allows Type 3 (inter-area) LSAs?',
    choices: [
      { id: 'a', text: 'Stub area' },
      { id: 'b', text: 'Totally stubby area' },
      { id: 'c', text: 'Backbone area' },
      { id: 'd', text: 'NSSA totally stubby' },
    ],
    correct: ['a'],
    explanation:
      'A stub area blocks Type 5 externals (using a default route instead) but still receives Type 3 summaries. A totally stubby area blocks Type 3 as well.',
    reference: '300-410 ENARSI — OSPF area types',
  }),
  q({
    id: 'np-redist-loop',
    domain: D.ROUTING,
    difficulty: 'Advanced',
    prompt:
      'When mutually redistributing between two protocols at multiple points, which technique best prevents routing loops?',
    choices: [
      {
        id: 'a',
        text: 'Tag routes on redistribution and deny tagged routes coming back with a route-map',
      },
      { id: 'b', text: 'Increase the OSPF reference bandwidth' },
      { id: 'c', text: 'Enable split horizon on all interfaces' },
      { id: 'd', text: 'Use the same metric for every redistributed route' },
    ],
    correct: ['a'],
    explanation:
      'Route tagging with route-maps lets each redistribution point identify and filter routes that originated in the other domain, preventing feedback loops.',
    reference: '300-410 ENARSI — redistribution',
  }),
  q({
    id: 'np-ospf-cost',
    domain: D.ROUTING,
    prompt: 'By default, how is an OSPF interface cost calculated?',
    choices: [
      { id: 'a', text: 'Reference bandwidth (100 Mbps) ÷ interface bandwidth' },
      { id: 'b', text: 'Interface bandwidth ÷ reference bandwidth' },
      { id: 'c', text: 'Sum of bandwidth and delay' },
      { id: 'd', text: 'Hop count to the destination' },
    ],
    correct: ['a'],
    explanation:
      'Cost = reference bandwidth / interface bandwidth (min 1). The default reference is 100 Mbps, so all links ≥100 Mbps get cost 1 unless you raise the reference with `auto-cost reference-bandwidth`.',
    reference: '350-401 ENCOR — OSPF metrics',
  }),

  // --- Enterprise Switching -------------------------------------------
  q({
    id: 'np-rstp-alternate',
    domain: D.SWITCHING,
    prompt:
      'In Rapid PVST+ (RSTP), which port role provides an alternate (backup) path toward the root bridge?',
    choices: [
      { id: 'a', text: 'Alternate port' },
      { id: 'b', text: 'Designated port' },
      { id: 'c', text: 'Root port' },
      { id: 'd', text: 'Edge port' },
    ],
    correct: ['a'],
    explanation:
      'RSTP replaces the old "blocking" state with Alternate (an alternate path to the root) and Backup (a backup to a designated port on the same segment) roles for fast convergence.',
    reference: '350-401 ENCOR — RSTP',
  }),
  q({
    id: 'np-lacp-combo',
    domain: D.SWITCHING,
    prompt: 'Which LACP mode combination successfully forms an EtherChannel?',
    choices: [
      { id: 'a', text: 'active / passive' },
      { id: 'b', text: 'passive / passive' },
      { id: 'c', text: 'auto / auto' },
      { id: 'd', text: 'on / active' },
    ],
    correct: ['a'],
    explanation:
      'LACP forms a bundle with active/active or active/passive. Passive/passive never initiates. "on" disables LACP and only bundles with another "on".',
    reference: '350-401 ENCOR — EtherChannel',
  }),
  q({
    id: 'np-stp-root-primary',
    domain: D.SWITCHING,
    prompt: 'Which command makes a switch the root bridge for VLAN 10 by lowering its priority?',
    choices: [
      { id: 'a', text: 'spanning-tree vlan 10 root primary' },
      { id: 'b', text: 'spanning-tree vlan 10 priority 40960' },
      { id: 'c', text: 'spanning-tree mode root vlan 10' },
      { id: 'd', text: 'switchport spanning-tree root 10' },
    ],
    correct: ['a'],
    explanation:
      '`spanning-tree vlan 10 root primary` sets the priority low enough (typically 24576) to win the root election. You can also set `priority` directly in multiples of 4096.',
    reference: '350-401 ENCOR — STP tuning',
  }),
  q({
    id: 'np-bpduguard',
    domain: D.SWITCHING,
    prompt: 'What does BPDU Guard do when a PortFast-enabled access port receives a BPDU?',
    choices: [
      { id: 'a', text: 'Puts the port into err-disabled state' },
      { id: 'b', text: 'Elects the port as root' },
      { id: 'c', text: 'Converts the port to a trunk' },
      { id: 'd', text: 'Silently forwards the BPDU' },
    ],
    correct: ['a'],
    explanation:
      'BPDU Guard err-disables an edge (PortFast) port the moment it receives a BPDU, protecting the topology from a rogue switch plugged into an access port.',
    reference: '350-401 ENCOR — STP protection',
  }),
  q({
    id: 'np-native-mismatch',
    domain: D.SWITCHING,
    prompt: 'A native VLAN mismatch on an 802.1Q trunk is typically reported by which protocol?',
    choices: [
      { id: 'a', text: 'CDP' },
      { id: 'b', text: 'STP root guard' },
      { id: 'c', text: 'LACP' },
      { id: 'd', text: 'VTP pruning' },
    ],
    correct: ['a'],
    explanation:
      'CDP detects and logs native VLAN mismatches between trunk neighbors. A mismatch can cause VLAN "leaking" between the two native VLANs.',
    reference: '350-401 ENCOR — trunking',
  }),

  // --- FHRP & High Availability ---------------------------------------
  q({
    id: 'np-hsrp-vmac',
    domain: D.REDUNDANCY,
    prompt: 'What is the format of an HSRP version 1 virtual MAC address for group N?',
    choices: [
      { id: 'a', text: '0000.0C07.ACxx (xx = group number in hex)' },
      { id: 'b', text: '0000.5E00.01xx' },
      { id: 'c', text: '0007.B400.00xx' },
      { id: 'd', text: 'The active router’s burned-in MAC' },
    ],
    correct: ['a'],
    explanation:
      'HSRPv1 uses 0000.0C07.ACxx where xx is the group. (VRRP uses 0000.5E00.01xx; GLBP uses 0007.B400.xxyy.)',
    reference: '350-401 ENCOR — FHRP',
  }),
  q({
    id: 'np-hsrp-preempt',
    domain: D.REDUNDANCY,
    prompt: 'What is the purpose of `standby <group> preempt` in HSRP?',
    choices: [
      { id: 'a', text: 'Let a higher-priority router reclaim the Active role when it returns' },
      { id: 'b', text: 'Encrypt HSRP hellos' },
      { id: 'c', text: 'Disable the virtual IP' },
      { id: 'd', text: 'Force both routers to be Active' },
    ],
    correct: ['a'],
    explanation:
      'Without preempt, a recovered higher-priority router stays Standby. `preempt` allows it to take back the Active role. Default priority is 100; higher wins.',
    reference: '350-401 ENCOR — HSRP',
  }),
  q({
    id: 'np-vrrp-multicast',
    domain: D.REDUNDANCY,
    prompt: 'Which multicast address does VRRP use for its advertisements?',
    choices: [
      { id: 'a', text: '224.0.0.18' },
      { id: 'b', text: '224.0.0.2' },
      { id: 'c', text: '224.0.0.102' },
      { id: 'd', text: '224.0.0.10' },
    ],
    correct: ['a'],
    explanation:
      'VRRP advertisements go to 224.0.0.18. (HSRPv1 uses 224.0.0.2/UDP 1985; GLBP uses 224.0.0.102/UDP 3222.)',
    reference: '350-401 ENCOR — VRRP',
  }),
  q({
    id: 'np-glbp-feature',
    domain: D.REDUNDANCY,
    difficulty: 'Advanced',
    prompt: 'What distinguishes GLBP from HSRP and VRRP?',
    choices: [
      { id: 'a', text: 'It load-balances traffic across multiple active forwarders in one group' },
      { id: 'b', text: 'It is an IETF open standard' },
      { id: 'c', text: 'It requires no virtual IP' },
      { id: 'd', text: 'It runs only on IPv6' },
    ],
    correct: ['a'],
    explanation:
      'GLBP’s Active Virtual Gateway (AVG) hands out different virtual MACs so multiple Active Virtual Forwarders (AVFs) share the load — unlike HSRP/VRRP where only one router forwards per group.',
    reference: '350-401 ENCOR — GLBP',
  }),

  // --- Network Services & QoS -----------------------------------------
  q({
    id: 'np-dscp-ef',
    domain: D.SERVICES,
    prompt: 'Which DSCP value is Expedited Forwarding (EF), typically used for voice?',
    choices: [
      { id: 'a', text: '46' },
      { id: 'b', text: '26' },
      { id: 'c', text: '34' },
      { id: 'd', text: '0' },
    ],
    correct: ['a'],
    explanation:
      'EF = DSCP 46, reserved for low-latency traffic like voice (a strict-priority/LLQ queue). AF classes (e.g. AF31=26, AF41=34) are assured forwarding.',
    reference: '350-401 ENCOR — QoS marking',
  }),
  q({
    id: 'np-shape-vs-police',
    domain: D.SERVICES,
    prompt: 'Which QoS mechanism BUFFERS traffic that exceeds a rate rather than dropping it?',
    choices: [
      { id: 'a', text: 'Traffic shaping' },
      { id: 'b', text: 'Traffic policing' },
      { id: 'c', text: 'WRED' },
      { id: 'd', text: 'Classification' },
    ],
    correct: ['a'],
    explanation:
      'Shaping buffers excess traffic and smooths bursts (adding delay). Policing drops or re-marks excess immediately, without buffering.',
    reference: '350-401 ENCOR — shaping vs policing',
  }),
  q({
    id: 'np-trust-boundary',
    domain: D.SERVICES,
    difficulty: 'Advanced',
    prompt: 'In QoS, what is the "trust boundary"?',
    choices: [
      { id: 'a', text: 'The point where incoming QoS markings are accepted as trustworthy' },
      { id: 'b', text: 'The link between two ISPs' },
      { id: 'c', text: 'The maximum queue depth' },
      { id: 'd', text: 'The boundary between IPv4 and IPv6' },
    ],
    correct: ['a'],
    explanation:
      'The trust boundary is where the network starts trusting DSCP/CoS markings — ideally as close to the source as possible (e.g. the access port facing an IP phone).',
    reference: '350-401 ENCOR — QoS trust',
  }),
  q({
    id: 'np-ipsla-track',
    domain: D.SERVICES,
    prompt: 'A common use of IP SLA combined with object tracking is to:',
    choices: [
      { id: 'a', text: 'Fail over a static default route when a probe stops reaching a target' },
      { id: 'b', text: 'Encrypt management traffic' },
      { id: 'c', text: 'Assign VLANs dynamically' },
      { id: 'd', text: 'Compress routing updates' },
    ],
    correct: ['a'],
    explanation:
      'IP SLA sends probes (ICMP, HTTP, UDP jitter…) and object tracking watches the result, so you can remove a static route (or lower HSRP priority) when the path fails.',
    reference: '300-410 ENARSI — IP SLA / tracking',
  }),
  q({
    id: 'np-ntp-stratum',
    domain: D.SERVICES,
    prompt: 'What does the NTP "stratum" value indicate?',
    choices: [
      { id: 'a', text: 'The number of hops from an authoritative time source' },
      { id: 'b', text: 'The polling interval in seconds' },
      { id: 'c', text: 'The clock’s accuracy in milliseconds' },
      { id: 'd', text: 'The UDP port NTP uses' },
    ],
    correct: ['a'],
    explanation:
      'Stratum measures distance from the reference clock: stratum 1 is directly attached to an authoritative source; each hop away increments it (max 15; 16 = unsynchronized).',
    reference: '350-401 ENCOR — NTP',
  }),

  // --- Overlay & Virtualization ---------------------------------------
  q({
    id: 'np-vrf-lite',
    domain: D.OVERLAY,
    prompt: 'What does VRF (VRF-lite) provide on a single router?',
    choices: [
      { id: 'a', text: 'Multiple independent routing/forwarding tables (path isolation)' },
      { id: 'b', text: 'Faster CPU switching' },
      { id: 'c', text: 'Automatic IP address assignment' },
      { id: 'd', text: 'Encryption of all interfaces' },
    ],
    correct: ['a'],
    explanation:
      'VRF creates separate routing tables so overlapping or isolated networks can coexist on one device — the basis for path isolation and MPLS L3VPN.',
    reference: '350-401 ENCOR — virtualization',
  }),
  q({
    id: 'np-vxlan-udp',
    domain: D.OVERLAY,
    difficulty: 'Advanced',
    prompt:
      'VXLAN encapsulates Layer 2 frames inside which transport, and on what destination port?',
    choices: [
      { id: 'a', text: 'UDP, port 4789' },
      { id: 'b', text: 'TCP, port 443' },
      { id: 'c', text: 'GRE, protocol 47' },
      { id: 'd', text: 'UDP, port 6081' },
    ],
    correct: ['a'],
    explanation:
      'VXLAN uses MAC-in-UDP encapsulation with destination UDP port 4789. Its 24-bit VNI allows ~16 million segments (vs 4094 VLANs).',
    reference: '350-401 ENCOR — VXLAN',
  }),
  q({
    id: 'np-vxlan-vni',
    domain: D.OVERLAY,
    prompt: 'How many bits is the VXLAN Network Identifier (VNI)?',
    choices: [
      { id: 'a', text: '24 bits (~16 million segments)' },
      { id: 'b', text: '12 bits (4094 segments)' },
      { id: 'c', text: '16 bits' },
      { id: 'd', text: '32 bits' },
    ],
    correct: ['a'],
    explanation:
      'The 24-bit VNI massively expands the L2 segment space compared to the 12-bit 802.1Q VLAN ID, which is why VXLAN scales for data centers/fabrics.',
    reference: '350-401 ENCOR — VXLAN',
  }),
  q({
    id: 'np-gre-tunnel-src',
    domain: D.OVERLAY,
    prompt: 'Which interface command sets the source of a GRE tunnel?',
    choices: [
      { id: 'a', text: 'tunnel source <interface|ip>' },
      { id: 'b', text: 'ip tunnel origin <ip>' },
      { id: 'c', text: 'set tunnel local <ip>' },
      { id: 'd', text: 'gre source <interface>' },
    ],
    correct: ['a'],
    explanation:
      'Under the tunnel interface you set `tunnel source` and `tunnel destination`; `tunnel mode gre ip` is the default. GRE (IP protocol 47) carries multiprotocol traffic but has no encryption.',
    reference: '350-401 ENCOR — GRE',
  }),

  // --- Infrastructure Security ----------------------------------------
  q({
    id: 'np-dai-binding',
    domain: D.SECURITY,
    prompt: 'Dynamic ARP Inspection (DAI) validates ARP packets against which data source?',
    choices: [
      { id: 'a', text: 'The DHCP snooping binding table' },
      { id: 'b', text: 'The CAM (MAC address) table' },
      { id: 'c', text: 'The CDP neighbor table' },
      { id: 'd', text: 'The routing table' },
    ],
    correct: ['a'],
    explanation:
      'DAI checks IP-to-MAC bindings learned by DHCP snooping (or static ARP ACLs), dropping ARPs that don’t match to stop ARP spoofing/MITM attacks.',
    reference: '350-401 ENCOR — Layer 2 security',
  }),
  q({
    id: 'np-dhcp-snoop-untrusted',
    domain: D.SECURITY,
    prompt:
      'On a DHCP snooping-enabled switch, which DHCP messages are dropped if received on an UNTRUSTED port?',
    choices: [
      { id: 'a', text: 'Server messages such as DHCPOFFER and DHCPACK' },
      { id: 'b', text: 'Client DHCPDISCOVER messages' },
      { id: 'c', text: 'All DHCP messages' },
      { id: 'd', text: 'Only DHCPRELEASE messages' },
    ],
    correct: ['a'],
    explanation:
      'Untrusted ports (facing hosts) may only send client messages. Server-sourced messages (OFFER/ACK) arriving there indicate a rogue DHCP server and are dropped. Uplinks to real servers are set `trust`.',
    reference: '350-401 ENCOR — DHCP snooping',
  }),
  q({
    id: 'np-copp',
    domain: D.SECURITY,
    difficulty: 'Advanced',
    prompt: 'What does Control Plane Policing (CoPP) protect?',
    choices: [
      { id: 'a', text: 'The device CPU/control plane from excessive or malicious traffic' },
      { id: 'b', text: 'User data traffic in the forwarding plane' },
      { id: 'c', text: 'The console port password' },
      { id: 'd', text: 'The DHCP pool from exhaustion' },
    ],
    correct: ['a'],
    explanation:
      'CoPP applies a QoS policy to traffic destined to the control plane (routing protocols, management, ARP), rate-limiting it so the CPU stays available during floods/DoS.',
    reference: '350-401 ENCOR — device hardening',
  }),
  q({
    id: 'np-tacacs',
    domain: D.SECURITY,
    prompt:
      'Which AAA protocol encrypts the ENTIRE packet body and separates authentication, authorization, and accounting?',
    choices: [
      { id: 'a', text: 'TACACS+ (TCP 49)' },
      { id: 'b', text: 'RADIUS (UDP 1812)' },
      { id: 'c', text: 'Kerberos' },
      { id: 'd', text: 'SNMPv3' },
    ],
    correct: ['a'],
    explanation:
      'TACACS+ (Cisco, TCP 49) encrypts the whole payload and cleanly separates AAA — great for granular command authorization. RADIUS encrypts only the password and combines authn+authz.',
    reference: '350-401 ENCOR — AAA',
  }),

  // --- Automation & Programmability -----------------------------------
  q({
    id: 'np-netconf',
    domain: D.AUTOMATION,
    prompt: 'NETCONF uses which transport and default port, and which data encoding?',
    choices: [
      { id: 'a', text: 'SSH, port 830, XML' },
      { id: 'b', text: 'HTTPS, port 443, JSON' },
      { id: 'c', text: 'Telnet, port 23, plain text' },
      { id: 'd', text: 'SNMP, port 161, ASN.1' },
    ],
    correct: ['a'],
    explanation:
      'NETCONF runs over SSH (TCP 830) and encodes data as XML, modeled with YANG. RESTCONF, by contrast, uses HTTP(S) with JSON or XML.',
    reference: '350-401 ENCOR — NETCONF/YANG',
  }),
  q({
    id: 'np-restconf',
    domain: D.AUTOMATION,
    prompt: 'RESTCONF is best described as:',
    choices: [
      { id: 'a', text: 'A REST API over HTTP(S) using JSON or XML, based on YANG models' },
      { id: 'b', text: 'A CLI scripting language' },
      { id: 'c', text: 'A replacement for SSH' },
      { id: 'd', text: 'A routing protocol' },
    ],
    correct: ['a'],
    explanation:
      'RESTCONF exposes YANG-modeled data through RESTful HTTP verbs (GET/POST/PUT/PATCH/DELETE) with JSON or XML payloads — simpler for web tooling than NETCONF.',
    reference: '350-401 ENCOR — RESTCONF',
  }),
  q({
    id: 'np-yaml',
    domain: D.AUTOMATION,
    prompt:
      'Which data format uses indentation for structure and is commonly used by Ansible playbooks?',
    choices: [
      { id: 'a', text: 'YAML' },
      { id: 'b', text: 'XML' },
      { id: 'c', text: 'CSV' },
      { id: 'd', text: 'Protobuf' },
    ],
    correct: ['a'],
    explanation:
      'YAML is a human-friendly, indentation-based superset of JSON. Ansible playbooks and many CI configs are written in YAML.',
    reference: '350-401 ENCOR — data formats',
  }),
  q({
    id: 'np-ansible',
    domain: D.AUTOMATION,
    prompt: 'Which statement about Ansible is TRUE?',
    choices: [
      { id: 'a', text: 'It is agentless and typically connects to network devices over SSH' },
      { id: 'b', text: 'It requires an agent installed on every device' },
      { id: 'c', text: 'It only works with Cisco devices' },
      { id: 'd', text: 'It uses a compiled binary pushed to each router' },
    ],
    correct: ['a'],
    explanation:
      'Ansible is agentless (push model) and reaches devices over SSH/API. Its tasks are idempotent, and playbooks are written in YAML. (Puppet/Chef use agents and a pull model.)',
    reference: '350-401 ENCOR — configuration management',
  }),
  q({
    id: 'np-json-object',
    domain: D.AUTOMATION,
    difficulty: 'Beginner',
    prompt: 'In JSON, which pair of characters denotes an object (key/value collection)?',
    choices: [
      { id: 'a', text: 'Curly braces { }' },
      { id: 'b', text: 'Square brackets [ ]' },
      { id: 'c', text: 'Parentheses ( )' },
      { id: 'd', text: 'Angle brackets < >' },
    ],
    correct: ['a'],
    explanation:
      'JSON objects use { } around comma-separated "key": value pairs; arrays use [ ]. Keys are strings; values can be string, number, boolean, null, object, or array.',
    reference: '350-401 ENCOR — JSON',
  }),
  q({
    id: 'np-eem',
    domain: D.AUTOMATION,
    difficulty: 'Advanced',
    prompt: 'What is Cisco EEM (Embedded Event Manager) used for?',
    choices: [
      { id: 'a', text: 'On-device, event-driven automation (react to syslog, counters, timers…)' },
      { id: 'b', text: 'Encrypting routing updates' },
      { id: 'c', text: 'Load-balancing across links' },
      { id: 'd', text: 'Compressing the running-config' },
    ],
    correct: ['a'],
    explanation:
      'EEM runs applets/scripts directly on the device that trigger on events (syslog patterns, SNMP, timers, CLI) and take actions — local automation without an external controller.',
    reference: '350-401 ENCOR — EEM',
  }),
  q({
    id: 'np-netmiko',
    domain: D.AUTOMATION,
    prompt:
      'Which Python library is purpose-built for SSH automation of network devices (multi-vendor)?',
    choices: [
      { id: 'a', text: 'Netmiko' },
      { id: 'b', text: 'NumPy' },
      { id: 'c', text: 'Flask' },
      { id: 'd', text: 'Matplotlib' },
    ],
    correct: ['a'],
    explanation:
      'Netmiko (built on Paramiko) simplifies SSH connections and command handling across many network OSes. For model-driven programmability you’d use ncclient (NETCONF) or requests (RESTCONF).',
    reference: '350-401 ENCOR — Python for networking',
  }),
]);
